version: '3'

services:
  web:
    build:
      context: ./
      # Run dev with dependencies only by targetting earlier build stage
      target: "deps"
    image: opstical/rockademy-client:dev
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      - CONNECTION_BASE_URL=http://localhost:3000
      - MONGODB_URI=mongodb://mongodb/rockademy_db
      - JWT_SECRET=mysecret
    volumes:
      # ignore hot-reloading node_modules by creating a seperate volume
      - .:/app
      - /app/node_modules/
    networks:
      - rockademy
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: unless-stopped
    # silence noisy log output
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: rockademy_db
    volumes:
      - mongodata:/data/db
    networks:
      - rockademy

networks:
  rockademy:


volumes:
  mongodata:
